### ISSUE TITLE
关于模型指标的问题

### ISSUE THREAD

**Issue by Hackerismydream** [LarryHawkingYoung/KDD2024_FedGTP#1]
作者你好，感谢你出色的工作，拜读了你的论文之后我又着手复现FedGTP，我有几个问题想请教一下：
1. 根据Figure4和Algorithm1中的表述，每个Client训练各自的模型（个性化联邦），最终得到关于每个Client的模型(W_i,b_i,P_i,E_i)，提供的代码工程文件似乎也并没有一个全局模型之类的可以衡量整体性能指标的模型，那最终在测试评估性能的时候，模型总的指标是怎么得到的呢？（具体而言，Table1和Table2中的指标是怎么计算的呢，是将所有客户端的评估结果聚合起来，以得到整体的性能指标，还是有其他的计算方法？）
2. 5.1节中的实验设置有提及到TaxiFlow-BJ 这个数据集，后续的章节和实验都没涉及到这个数据集，这个数据集的作用是什么呢？
感谢作者大大抽空回复

**Comment by LarryHawkingYoung** [comment]
Hi Wanjia, 感谢你对我们工作的关注，关于你的问题：

1. Table 1和2中的性能指标，是各方单独计算性能指标之后，平均聚合得到的结果

2. TaxiFlow-BJ由于是真实天然（而非人为划分）联邦的私有数据集，因此我们将其运用于实验的case study部分，在文中对应部分是有提到的

**Comment by LarryHawkingYoung** [comment]
Hi Wanjia, 感谢你对我们工作的关注，关于你的问题： 
1. Table 1和2中的性能指标，是各方单独计算性能指标之后，平均聚合得到的结果 
2. TaxiFlow-BJ由于是真实天然（而非人为划分）联邦的私有数据集，因此我们将其运用于实验的case study部分，在文中对应部分是有提到的
---- 回复的原邮件 ----
发件人Huang ***@***.***>发送日期2024年08月26日 05:44 ***@***.***> ***@***.***>主题[LarryHawkingYoung/KDD2024_FedGTP] 关于模型指标的问题 (Issue #1)
作者你好，感谢你出色的工作，拜读了你的论文之后我又着手复现FedGTP，我有几个问题想请教一下：
根据Figure4和Algorithm1中的表述，每个Client训练各自的模型（个性化联邦），最终得到关于每个Client的模型(W_i,b_i,P_i,E_i)，提供的代码工程文件似乎也并没有一个全局模型之类的可以衡量整体性能指标的模型，那最终在测试评估性能的时候，模型总的指标是怎么得到的呢？（具体而言，Table1和Table2中的指标是怎么计算的呢，是将所有客户端的评估结果聚合起来，以得到整体的性能指标，还是有其他的计算方法？）
5.1节中的实验设置有提及到TaxiFlow-BJ 这个数据集，后续的章节和实验都没涉及到这个数据集，这个数据集的作用是什么呢？
感谢作者大大抽空回复

**Comment by Hackerismydream** [comment]
> Hi Wanjia, 感谢你对我们工作的关注，关于你的问题：
> 
> 1. Table 1和2中的性能指标，是各方单独计算性能指标之后，平均聚合得到的结果
> 2. TaxiFlow-BJ由于是真实天然（而非人为划分）联邦的私有数据集，因此我们将其运用于实验的case study部分，在文中对应部分是有提到的

我清楚了，再次感谢你们出色的工作和回复^ ^
